[package]
name = "GetMyIP"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "GetMyIP"
path = "src/request.rs"


[dependencies]
reqwest = "0.11"
async-std = "1.10"
tokio = { version = "1", features = ["full"] }

